# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94589fa2205c590dc2f4ffe901808cf10436794a542e3c48317fdea503986064b456905b7c2476b65b335d124c62693f66b510aa0eb8879eb1bc5d0625ad34bf

test:
  secret_key_base: 351a25657c38d1f7996b15934197fc80a20d2f73ab6a75275105cbd037b065ab0020c383ef374b53a9beaf4f2db6ba142a1c3e071ef2ad7b4d06dd742542c5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
